### your site title here

title: Always Prototype
baseurl: "" # name of the repository
email: rise.shia@gmail.com
github: riseshia
linkedin: shiasim
author: Shia

kramdown:
  input: GFM
### exclude the instructions / write-up in the README.md

# Tracker
analytics: UA-71964698-1

#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

paginate: 15

sass:
 style: compressed

exclude:
- README.md

gems: [jekyll-seo-tag, jekyll-paginate]
